# Generated by Django 3.2.2 on 2021-05-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartmentproduct',
            old_name='produc6_id',
            new_name='product_id',
        ),
    ]
